### ISSUE TITLE
Update Grade Tracker

### ISSUE THREAD

**Issue by abbywingo** [abbywingo/test-app#2]
- [ ] clear grade tracker functionality
- [ ] by default, show classes for current semester
- [ ] add dropdown in tabs to select a class from other semesters
- [ ] make add/edit class modals multiple pages w/ progress tracker
- [ ] default nav to first class listed
- [ ] allow for final grade and assignment categories to have different grading types
